name: Build

on:
  push:
    branches: [ 'master', 'renovate/**' ]
    paths-ignore: [ 'webapp/**' ]
  pull_request:
    branches: [ 'master', 'renovate/**' ]
    paths-ignore: [ 'webapp/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

#    - name: Upload code coverage results
#      uses: codecov/codecov-action@v4
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        directory: ./core/build/reports/jacoco/test/

#    - name: Run Codacy Analysis CLI
#      uses: codacy/codacy-analysis-cli-action@v4
#      with:
#        output: results.sarif
#        format: sarif
#        gh-code-scanning-compat: true
#        max-allowed-issues: 2147483647
#    - name: Upload SARIF results file
#      uses: github/codeql-action/upload-sarif@main
#      with:
#        sarif_file: results.sarif