#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_sunstorm_showmanager_ltc_LibLTCWrapper */

#ifndef _Included_me_sunstorm_showmanager_ltc_LibLTCWrapper
#define _Included_me_sunstorm_showmanager_ltc_LibLTCWrapper
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     me_sunstorm_showmanager_ltc_LibLTCWrapper
	 * Method:    init
	 * Signature: (II)V
	 */
	JNIEXPORT void JNICALL Java_me_sunstorm_showmanager_ltc_LibLTCWrapper_init
	(JNIEnv*, jobject, jint, jint);

	/*
	 * Class:     me_sunstorm_showmanager_ltc_LibLTCWrapper
	 * Method:    setTime
	 * Signature: (IIII)V
	 */
	JNIEXPORT void JNICALL Java_me_sunstorm_showmanager_ltc_LibLTCWrapper_setTime
	(JNIEnv*, jobject, jint, jint, jint, jint);

	/*
	* Class:     me_sunstorm_showmanager_ltc_LibLTCWrapper
	* Method:    getData
	* Signature: ()[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_me_sunstorm_showmanager_ltc_LibLTCWrapper_getData
	(JNIEnv*, jobject);

	/*
	 * Class:     me_sunstorm_showmanager_ltc_LibLTCWrapper
	 * Method:    free
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_me_sunstorm_showmanager_ltc_LibLTCWrapper_free
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
